### ISSUE TITLE
[Issue] Crash on startup

### ISSUE THREAD

**Issue by accessdenied0** [Alec-WAM/CrystalMod#18]
Minecraft Version:  1.10.2
Forge Version:  1.10.2-12.18.3.2239 (Newest)
Mod Version:  3.2.0dev

Is this on a server yes/no:  No

Crash Log(s) if applicable (pastebin or git):  http://pastebin.com/U42TAB9y

Steps to reproduce:  
Just start the game with my (own customized) modpack... (might be a compat error?)

Hey @Alec-WAM,

I hope this version is still supported and hope you can give me some help.

thank you in advice

access_deneid

**Comment by Alec-WAM** [comment]
OK so I cant tell the error. Right were this error is printed in the crash log it lists the code line numbers. These numbers do not match any of the numbers in my code. Specifically the line that lists (ModCrafting 534).

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Crystal Mod (CrystalMod)
Caused by: java.lang.NullPointerException
    at net.minecraft.item.crafting.CraftingManager.func_92103_a(SourceFile:1199)
    at net.minecraftforge.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:230)
    at alec_wam.CrystalMod.crafting.ModCrafting.addShapedRecipe(ModCrafting.java:534)
    at alec_wam.CrystalMod.crafting.ModCrafting.init(ModCrafting.java:444)
    at alec_wam.CrystalMod.proxy.CommonProxy.init(CommonProxy.java:122)
    at alec_wam.CrystalMod.proxy.ClientProxy.init(ClientProxy.java:90)
    at alec_wam.CrystalMod.CrystalMod.init(CrystalMod.java:213)

It looks like you were correct with the incompatibility. I am willing to update the mod for 1.10.2 if you cant find any mod incompatibility.

**Comment by accessdenied0** [comment]
@Alec-WAM,

Thank you a lot^^

I sadly can't really tell which mod it causes. I could try the mod in some of my other packs to get a better overview. (I would guess Crafting Tweaker, Forestry, IC2, Mod Tweaker, Avaritia or so on... all these mods who uses the Crafting Manager or add them one by their own) 
But never less I would be really thankful if you could fix it!

I thank you again for your help.

access_denied

**Comment by Alec-WAM** [comment]
I doubt this has anything to do with Crafting Tweaks but I will ping @blay09 to check this out.

**Comment by Zygus42** [comment]
CrystalMod-1.10.2-3.2.0dev, forge-1.10.2-12.18.3.2254.

Same crash.  Error report:
[crash-2017-03-17_10.40.28-client.txt](https://github.com/Alec-WAM/CrystalMod/files/849515/crash-2017-03-17_10.40.28-client.txt)
